name: 'Quality-UO'
description: 'Configure and Quality-UO Static Analysis Tool'
inputs: 
  passname: 
    description: 'Name of pass to build' 
    required: true 
    default: all 
runs: 
  using: 'docker'
  image: '../../../src/dockerStuff/Dockerfile' 
  volumes: '../../../src/static:/static'
  options: 
    name: 'quality-uo'
  # args: 
  #   - ${{ inputs.passname }}