on: [push]

jobs: 
  Configure-Quality-UO-Tool: 
    runs-on: ubuntu-latest 
    name: Configure and build static analysis tool 
    steps: 
      - name: Checkout Code 
        uses: actions/checkout@v1 

      - name: Docker Image Build Step 
        uses: './.github/workflows/actions' 

      - name: Tool Build Setup Step  
        run: | 
          docker exec uoquality mkdir static/build 
          docker exec -w /static/build uoquality cmake .. 

      - name: Build visit-switch
        run: | 
          docker exec -w /static/build uoquality make visit-switch 