on: [push]

jobs: 
  Configure-Quality-UO-Tool: 
    runs-on: ubuntu-latest 
    name: Configure and build static analysis tool 
    container:
      image: './src/dockerStuff/Dockerfile'
      volumes: 
        - './src/static:/static'
      options: 
        name: 'quality-uo'
    steps: 
      - name: Checkout Code 
        uses: actions/checkout@v1 

      # - name: Docker Image Build Step 
      #   uses: './.github/workflows/actions' 
      #   # with: 
      #   #   passname: 'visit-switch'

      - name: Tool Build Setup Step  
        run: | 
          docker exec quality-uo mkdir static/build 
          docker exec -w /static/build quality-uo cmake .. 

      - name: Build visit-switch
        run: | 
          docker exec -w /static/build quality-uo make visit-switch 