on: [push]

jobs: 
  Configure-Quality-UO-Tool: 
    runs-on: ubuntu-latest 
    name: Configure and build static analysis tool 
    steps: 
      - name: Checkout 
        uses: actions/checkout@v3 
      - name: Docker image build step 
        uses: ${{ github.workspace }}/.github/workflows/actions/mydocker.yml  
        id: static-tool