on: [push]

jobs: 
  Configure-Quality-UO-Tool: 
    runs-on: ubuntu-latest 
    name: Configure and build static analysis tool 
    # container:
    #   image: ecpe4s/llvm-doe-oneapi:2022-01-31
    steps: 
      - name: Checkout 
        uses: actions/checkout@v1 
      # - name: Docker image build step 
      #   uses: './actions'  
      #   id: static-tool
      - run: ls $pwd
      - run: .